-- =============================================================
-- The Muslim World — Database Seed
-- =============================================================
-- Contains the full schema and data for the `sites` and
-- `hotspots` tables.
--
-- Usage (restore from scratch):
--   psql "$DATABASE_URL" -f lib/db/seed.sql
--
-- The script is idempotent: tables/sequences are created only
-- if they do not already exist, and INSERT uses ON CONFLICT DO
-- NOTHING so it is safe to re-run against an existing database.
-- =============================================================

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);

-- ── Schema ────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.sites (
    id                 integer NOT NULL,
    name               text NOT NULL,
    arabic_name        text NOT NULL,
    region             text NOT NULL,
    country            text NOT NULL,
    latitude           double precision NOT NULL,
    longitude          double precision NOT NULL,
    category           text NOT NULL,
    short_description  text NOT NULL,
    full_description   text NOT NULL,
    year_founded       text,
    significance       text NOT NULL,
    is_featured        boolean DEFAULT false NOT NULL,
    image_url          text,
    architectural_style text,
    created_at         timestamp without time zone DEFAULT now(),
    model_url          text,
    capacity           integer,
    area_sqm           integer,
    dual_use           text,
    eid_prayer         boolean DEFAULT false NOT NULL,
    ramadan_visit      boolean DEFAULT false NOT NULL,
    juma_prayer        boolean DEFAULT false NOT NULL,
    sect               text,
    CONSTRAINT sites_pkey PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS public.sites_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE ONLY public.sites ALTER COLUMN id SET DEFAULT nextval('public.sites_id_seq'::regclass);

CREATE TABLE IF NOT EXISTS public.hotspots (
    id               integer NOT NULL,
    site_id          integer NOT NULL,
    label            text NOT NULL,
    description      text NOT NULL,
    position_x       double precision NOT NULL,
    position_y       double precision NOT NULL,
    position_z       double precision NOT NULL,
    arabic_term      text,
    historical_period text,
    image_url        text,
    CONSTRAINT hotspots_pkey PRIMARY KEY (id),
    CONSTRAINT hotspots_site_id_sites_id_fk FOREIGN KEY (site_id) REFERENCES public.sites(id)
);

CREATE SEQUENCE IF NOT EXISTS public.hotspots_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE ONLY public.hotspots ALTER COLUMN id SET DEFAULT nextval('public.hotspots_id_seq'::regclass);

-- ── Sites data ─────────────────────────────────────────────────

INSERT INTO public.sites VALUES (1, 'Masjid Al-Haram', 'المسجد الحرام', 'Arabian Peninsula', 'Saudi Arabia', 21.4225, 39.8262, 'mosque', 'The holiest mosque in Islam, surrounding the Kaaba in Mecca.', 'Masjid Al-Haram is the largest mosque in the world and surrounds one of Islam''s holiest sites, the Kaaba. Located in Mecca, Saudi Arabia, it is the focal point of the Hajj pilgrimage and Umrah. Muslims around the world face toward the Kaaba during their daily prayers. The mosque has been expanded numerous times throughout history and can accommodate millions of worshippers simultaneously. Its current structure features massive minarets, grand archways, and the iconic clock tower complex.', 'c. 638 CE (major expansion)', 'The holiest site in Islam; direction of prayer (Qibla) for 1.8 billion Muslims worldwide', true, NULL, 'Islamic, Ottoman, modern expansions', '2026-05-23 18:51:05.682354', '/models/masjid-al-haram.glb', 2500000, 356800, NULL, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (2, 'Masjid An-Nabawi', 'المسجد النبوي', 'Arabian Peninsula', 'Saudi Arabia', 24.4672, 39.6112, 'mosque', 'The Prophet''s Mosque in Medina, built by Prophet Muhammad (PBUH).', 'Masjid An-Nabawi, the Prophet''s Mosque, was built by the Prophet Muhammad (PBUH) in 622 CE in Medina. It is the second holiest site in Islam after Masjid Al-Haram. The mosque contains the tomb of the Prophet Muhammad (PBUH), making it a site of immense spiritual significance. The iconic Green Dome marks the resting place of the Prophet. Over the centuries, the mosque has been expanded by various caliphs and sultans, and today it can accommodate over one million worshippers. It features beautiful calligraphy, retractable umbrellas in the courtyard, and the famous Riyad al-Jannah garden.', '622 CE', 'Second holiest site in Islam; resting place of Prophet Muhammad (PBUH)', true, NULL, 'Ottoman-Islamic with modern expansion', '2026-05-23 18:51:08.019512', '/models/masjid-an-nabawi.glb', 1000000, 98500, NULL, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (3, 'Masjid Al-Aqsa', 'المسجد الأقصى', 'Levant', 'Palestine', 31.7781, 35.236, 'mosque', 'The third holiest mosque in Islam, located on the Temple Mount in Jerusalem.', 'Masjid Al-Aqsa, meaning ''the farthest mosque'', is the third holiest site in Islam. Located in the Old City of Jerusalem, it holds immense religious significance as the site to which Prophet Muhammad (PBUH) made his night journey (Isra) and from which he ascended to the heavens (Miraj). The compound, known as Haram al-Sharif, also includes the Dome of the Rock with its magnificent golden dome. The mosque has been a center of Islamic civilization and scholarship for over 1,400 years. It was the first Qibla (direction of prayer) for early Muslims.', '705 CE (current structure)', 'Third holiest site in Islam; destination of Prophet''s Night Journey (Isra wal Miraj)', true, '/models/masjid-al-aqsa.obj', 'Early Islamic, Umayyad, Crusader modifications, Ayyubid', '2026-05-23 18:51:10.067882', NULL, 400000, 144000, NULL, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (4, 'Dome of the Rock', 'قبة الصخرة', 'Levant', 'Palestine', 31.7783, 35.2354, 'shrine', 'An Islamic shrine on the Temple Mount with its iconic golden dome.', 'The Dome of the Rock is an Islamic shrine located on the Temple Mount in Jerusalem, built by Umayyad Caliph Abd al-Malik ibn Marwan in 691-692 CE. It is one of the oldest extant works of Islamic architecture. The shrine''s golden dome is one of the most recognizable images in the world. It was built over the Foundation Stone, which holds profound significance in Jewish, Christian, and Islamic traditions. The interior features stunning Byzantine and early Islamic mosaics, intricate geometric patterns, and Quranic inscriptions.', '691-692 CE', 'One of oldest Islamic monuments; marks site of Prophet''s ascension to heavens', true, NULL, 'Umayyad Islamic, Byzantine influence', '2026-05-23 18:51:12.277463', NULL, 5000, 1500, NULL, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (5, 'Hagia Sophia', 'آيا صوفيا', 'Anatolia', 'Turkey', 41.0086, 28.9802, 'mosque', 'A magnificent structure in Istanbul converted to a mosque under Ottoman Sultan Mehmed II.', 'Hagia Sophia (Ayasofya) is a magnificent architectural wonder in Istanbul, Turkey. Originally built as a Christian cathedral in 537 CE, it was converted to a mosque after the Ottoman conquest of Constantinople in 1453 CE by Sultan Mehmed II. The building served as the principal mosque of Istanbul for nearly 500 years. It became a museum in 1934 but was reconverted to a mosque in 2020. The structure is famous for its massive dome, stunning Byzantine mosaics, and grand interior. It represents a unique architectural heritage spanning Byzantine and Ottoman Islamic traditions.', '1453 CE (converted to mosque)', 'Symbol of Ottoman triumph; architectural marvel blending Byzantine and Islamic heritage', true, NULL, 'Byzantine-Islamic, Ottoman additions', '2026-05-23 18:51:14.335231', NULL, 10000, 7300, 'Mosque & Museum', false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (6, 'Blue Mosque', 'مسجد السلطان أحمد', 'Anatolia', 'Turkey', 41.0054, 28.9768, 'mosque', 'Sultan Ahmed Mosque, famous for its six minarets and blue Iznik tiles.', 'The Sultan Ahmed Mosque, popularly known as the Blue Mosque due to the blue Iznik tiles adorning its interior, was built between 1609 and 1616 CE during the reign of Ottoman Sultan Ahmed I. Located in Istanbul, it is famous for its six minarets — an unusual number that caused controversy as it matched the minarets of the mosque in Mecca. The mosque features a cascade of domes and semi-domes, and its grand interior is decorated with over 20,000 hand-painted blue and white Iznik tiles. It remains an active mosque and one of Istanbul''s most iconic landmarks.', '1609-1616 CE', 'Masterpiece of Ottoman architecture; famous for unique six minarets and blue Iznik tile interior', false, NULL, 'Classical Ottoman', '2026-05-23 18:51:16.267988', NULL, 10000, 5000, NULL, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (7, 'Great Mosque of Cordoba', 'المسجد الكبير في قرطبة', 'Andalusia', 'Spain', 37.8789, -4.7794, 'mosque', 'The Mezquita, a stunning example of Moorish architecture in southern Spain.', 'The Great Mosque of Cordoba (Mezquita) is one of the finest examples of Moorish architecture in the world, located in Cordoba, Spain. Built during the Umayyad Caliphate of Cordoba beginning in 784 CE, it was expanded by subsequent rulers over two centuries. The mosque features the iconic forest of columns with distinctive red-and-white striped arches, intricate geometric mosaics, and a spectacular mihrab. During the height of Islamic Spain (Al-Andalus), Cordoba was one of the most advanced cities in Europe, and this mosque was its crown jewel. A cathedral was later built within the mosque during the Spanish Reconquista.', '784 CE', 'Crown jewel of Al-Andalus Islamic civilization; UNESCO World Heritage Site', true, '/site-images/cordoba.png', 'Umayyad Moorish (Andalusian)', '2026-05-23 18:51:18.368029', NULL, 25000, 23400, 'Mosque & Historic Monument', false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (8, 'Alhambra Palace', 'قصر الحمراء', 'Andalusia', 'Spain', 37.176, -3.5882, 'palace', 'The jewel of Islamic palatial architecture in Granada, Spain.', 'The Alhambra is a palace and fortress complex located in Granada, Spain, built during the Nasrid dynasty in the 13th-14th centuries CE. It represents the pinnacle of Islamic palatial architecture in Western Europe and is considered one of the finest examples of Islamic art and architecture in existence. The palace complex features stunning geometric tilework, intricate muqarnas (honeycomb vaulting), elegant courtyards with reflecting pools, lush gardens, and delicate stucco arabesques. The Court of the Lions with its famous marble fountain is among the most celebrated spaces in Islamic architecture.', 'c. 1238-1358 CE', 'Pinnacle of Nasrid Islamic architecture; UNESCO World Heritage Site; last great Islamic kingdom in Spain', true, '/site-images/alhambra.png', 'Nasrid Islamic (Andalusian)', '2026-05-23 18:51:20.502231', NULL, 40000, 142000, NULL, false, false, false, 'Universal') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (9, 'Imam Mosque', 'مسجد الإمام', 'Persia', 'Iran', 32.6565, 51.677, 'mosque', 'A masterpiece of Safavid Islamic architecture in Isfahan''s Naqsh-e Jahan Square.', 'The Imam Mosque (formerly Shah Mosque) in Isfahan, Iran, is widely considered one of the most beautiful mosques in the world and a supreme achievement of Persian Islamic architecture. Built during the Safavid dynasty under Shah Abbas I between 1611 and 1629 CE, it stands on the southern side of Naqsh-e Jahan Square, a UNESCO World Heritage Site. The mosque is famous for its resplendent tiled facade, massive portal, twin minarets, and a spectacular main dome covered in mosaic faience tilework in shades of blue, turquoise, and gold. The acoustic properties of the main dome are extraordinary.', '1611-1629 CE', 'Masterpiece of Safavid Persian Islamic art; UNESCO World Heritage Site', false, NULL, 'Safavid Persian Islamic', '2026-05-23 18:51:22.544827', NULL, 20000, 20000, NULL, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (10, 'Badshahi Mosque', 'بادشاہی مسجد', 'South Asia', 'Pakistan', 31.5882, 74.3104, 'mosque', 'One of the world''s largest mosques, a Mughal masterpiece in Lahore.', 'The Badshahi Mosque in Lahore, Pakistan, is one of the most iconic examples of Mughal architecture. Built by the sixth Mughal Emperor Aurangzeb between 1671 and 1673 CE, it was the world''s largest mosque for over three centuries. The mosque features a grand red sandstone exterior with white marble domes and minarets, beautiful geometric patterns, and exquisite marble inlay work. The main prayer hall can accommodate 10,000 worshippers, while the courtyard can hold up to 95,000. The mosque stands as a testament to the grandeur of the Mughal Empire at its zenith.', '1671-1673 CE', 'Greatest Mughal architectural achievement; symbol of Lahore and Pakistan', false, NULL, 'Mughal Islamic', '2026-05-23 18:51:26.467284', NULL, 100000, 26500, NULL, false, false, false, 'Sunni') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (11, 'Jama Masjid Delhi', 'جامع مسجد دهلي', 'South Asia', 'India', 28.6507, 77.2334, 'mosque', 'India''s largest mosque, built by Mughal Emperor Shah Jahan.', 'The Jama Masjid of Delhi is India''s largest mosque and one of the most magnificent examples of Mughal architecture. Commissioned by Mughal Emperor Shah Jahan and completed in 1656 CE, it was built with red sandstone and white marble. The mosque features three great gates, four towers, and two 40-metre minarets. The courtyard can hold over 25,000 worshippers. The mosque''s name means ''World-Reflecting Mosque.'' Shah Jahan also built the Taj Mahal, and the Jama Masjid shares similar architectural elements with that iconic monument.', '1644-1656 CE', 'India''s largest mosque; finest example of Mughal religious architecture', false, '/models/jamia-masjid-delhi.glb', 'Mughal Islamic', '2026-05-23 18:51:28.673378', NULL, 25000, 5700, NULL, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (12, 'Kairouan Great Mosque', 'جامع القيروان الكبير', 'North Africa', 'Tunisia', 35.6824, 10.0994, 'mosque', 'One of the oldest and most important mosques in North Africa.', 'The Great Mosque of Kairouan, also known as the Mosque of Uqba, is one of the oldest and most prestigious mosques in the Islamic world. Founded in 670 CE by the Arab general Uqba ibn Nafi, it is considered the fourth holiest site in Islam and a UNESCO World Heritage Site. The mosque served as a model for later Islamic architecture in the western Mediterranean. Its square minaret is considered the oldest surviving minaret in the world. The mosque''s prayer hall features a forest of columns, many reused from ancient Roman and Byzantine structures. Kairouan was a major center of Islamic learning in the early centuries of Islam.', '670 CE', 'Fourth holiest site in Islam; oldest mosque in North Africa; mother of North African mosques', false, NULL, 'Early Islamic (Aghlabid)', '2026-05-23 18:51:30.858364', NULL, 20000, 9000, NULL, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (13, 'Djinguereber Mosque', 'مسجد جنكريبر', 'Sub-Saharan Africa', 'Mali', 16.7716, -3.0054, 'mosque', 'A 14th-century mosque in Timbuktu, built using traditional Sudano-Sahelian architecture.', 'The Djinguereber Mosque is a famous and historic mosque in Timbuktu, Mali, built in 1327 CE. It was commissioned by Mansa Musa, the immensely wealthy Emperor of the Mali Empire, following his return from Hajj to Mecca. The mosque was designed by the Andalusian poet and architect Abou Es Haq Es Saheli. Built in the traditional Sudano-Sahelian architectural style using mud bricks and timber, it can accommodate 2,000 worshippers. Timbuktu was once a great center of Islamic learning, and the mosque is part of the city''s UNESCO World Heritage designation.', '1327 CE', 'Built by Mansa Musa after his legendary Hajj; center of medieval Sub-Saharan Islamic learning', false, NULL, 'Sudano-Sahelian', '2026-05-23 18:51:32.985429', NULL, 2000, 1300, NULL, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (14, 'Sultan Qaboos Grand Mosque', 'جامع السلطان قابوس الأكبر', 'Arabian Peninsula', 'Oman', 23.6088, 58.564, 'mosque', 'Oman''s grand national mosque, featuring the world''s largest hand-woven carpet.', 'The Sultan Qaboos Grand Mosque in Muscat, Oman, is one of the most impressive mosques in the world. Built between 1995 and 2001 CE, it was a gift from Sultan Qaboos bin Said Al Said to the people of Oman. The mosque can accommodate 20,000 worshippers. It is famous for housing the world''s largest hand-woven carpet, measuring 4,343 square meters and weighing 21 tons, and one of the world''s largest chandeliers. The prayer hall features a stunning interior dome and intricate Islamic geometric patterns. The mosque welcomes non-Muslim visitors and serves as a symbol of Oman''s Islamic identity.', '1995-2001 CE', 'Symbol of Oman''s Islamic heritage; houses world''s largest hand-woven carpet', false, NULL, 'Contemporary Islamic with traditional elements', '2026-05-23 18:51:35.202178', NULL, 20000, 416000, NULL, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (15, 'Da Tok Mosque', 'مسجد داتوك', 'Southeast Asia', 'Thailand', 6.8564, 101.3111, 'mosque', 'A historic brick mosque in Pattani, southern Thailand, restored by the governor of Yaring.', 'Da Tok Mosque (MAHS-THA-PTN-YAR-LMP-S-001-F-0001) stands south of Makam Tok Payang within a densely populated village, surrounded closely by houses. The complex includes a renovated mosque building and a large graveyard, each enclosed by separate walls. Once dilapidated and abandoned, the mosque was later restored and enlarged by Phraya Phiphit Senamat, governor of Yaring. Built of brick, plastered with lime, and painted white, it has a rectangular west-facing plan, balconies, colored glass windows, a dome, spiral staircase, and eastern extension.', NULL, 'A culturally significant mosque in the Muslim heartland of southern Thailand, representing the blend of Malay-Islamic and colonial architectural traditions.', true, NULL, 'Malay-Islamic with colonial influences', '2026-05-23 20:16:04.967304', '/models/da-tok-mosque.glb', 3000, 1200, NULL, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (16, 'Masjid al-Qiblatayn', 'مسجد القبلتين', 'Arabian Peninsula', 'Saudi Arabia', 24.4972, 39.5983, 'mosque', 'The Mosque of the Two Qiblas — where the direction of prayer was divinely changed from Jerusalem to Mecca.', 'Masjid al-Qiblatayn, meaning the Mosque of the Two Qiblas, stands as one of the most historically significant mosques in Islam. It was here, during the second year of Hijra (623 CE), that the Prophet Muhammad (PBUH) received the divine revelation commanding the change of the qibla — the direction of prayer — from Masjid al-Aqsa in Jerusalem to the Masjid al-Haram in Mecca. According to tradition, the Prophet was leading the Dhuhr (midday) prayer when the revelation descended, and he pivoted mid-prayer to face the new direction. The congregation turned with him, marking a defining moment in Islamic worship. The original structure was modest, but the mosque has been expanded and renovated multiple times, most extensively by the Saudi government in 1987. Today it stands as a radiant white marble structure adorned with two mihrab niches — one facing Jerusalem and one facing Mecca — symbolising the historic transition.', '2 AH (623 CE)', 'The only mosque in Islamic history where the qibla changed mid-prayer, marking the shift in the direction of prayer from Jerusalem to Mecca as commanded by divine revelation.', true, NULL, 'Contemporary Islamic — white marble with twin minarets and dual mihrabs', '2026-05-24 19:52:41.773291', '/models/masjid-al-qiblatayn.glb', 2000, 800, NULL, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (17, 'Al-Azhar Mosque', 'الجامع الأزهر', 'North Africa', 'Egypt', 30.0459, 31.2621, 'mosque', 'One of Islam''s oldest universities and the world''s pre-eminent centre of Sunni Islamic scholarship.', 'Founded in 970 CE by the Fatimid dynasty, Al-Azhar Mosque in Cairo is among the oldest continually operating universities in the world. Its name means "The Resplendent" and it serves as the global reference point for Sunni Islamic jurisprudence, theology, and Arabic language. The mosque''s multi-period architecture reflects a thousand years of patronage from successive dynasties — Fatimid, Ayyubid, Mamluk, and Ottoman — each leaving distinctive minarets and gateways. Al-Azhar University, attached to the mosque, draws students from over 100 countries and issues scholarly opinions (fatwas) followed by millions globally.', '970 CE', 'The most influential centre of Sunni Islamic learning; home of Al-Azhar University whose scholars have shaped Islamic thought for over 1,000 years', true, '/site-images/al-azhar.png', 'Fatimid–Mamluk composite', '2026-05-24 20:46:56.68185', '/models/al-azhar-mosque.glb', 20000, 12000, 'Mosque & University', false, false, false, 'Sunni') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (18, 'Faisal Mosque', 'مسجد فيصل', 'South Asia', 'Pakistan', 33.7294, 73.0369, 'Mosque', 'The iconic shell-shaped national mosque of Pakistan in Islamabad, one of the largest mosques in the world.', 'Faisal Mosque is the national mosque of Pakistan, located in Islamabad at the foot of the Margalla Hills. It was designed by Turkish architect Vedat Dalokay and funded by King Faisal bin Abdul Aziz of Saudi Arabia, after whom it is named. Construction began in 1976 and was completed in 1986. The mosque departs radically from traditional domed mosque architecture — its prayer hall is shaped like a Bedouin tent and flanked by four soaring minarets, creating a silhouette unlike any other mosque in the world. The main prayer hall can accommodate up to 74,000 worshippers inside, with the surrounding grounds holding an additional 200,000. It served as the largest mosque in the world from 1986 to 1993.', '1986', 'National mosque of Pakistan and an icon of contemporary Islamic architecture, blending Mughal heritage with modernist design.', false, NULL, 'Contemporary Islamic / Neo-Futurist', '2026-05-26 12:32:52.610071', '/models/faisal-mosque.glb', 300000, 54000, NULL, false, false, false, 'Sunni') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (19, 'Katara Mosque', 'مسجد كتارا', 'Arabian Peninsula', 'Qatar', 25.3726, 51.5255, 'Mosque', 'A stunning modern mosque in the Katara Cultural Village of Doha, blending Andalusian and Levantine Islamic aesthetics.', 'The Katara Mosque, also known as the Grand Mosque of Katara, is set within the Katara Cultural Village on the shores of Doha, Qatar. Completed around 2010, the mosque reflects a synthesis of Andalusian, Ottoman, and Levantine architectural traditions — featuring a grand central dome, intricate geometric tilework, colonnaded arcades, and a single elegant minaret. It serves the cultural village community and visitors as both a place of worship and an architectural landmark. The exterior is clad in blue and white Andalusian-inspired faience tiles, while the interior features hand-painted ceilings, marble floors, and delicate arabesque carvings. The mosque is surrounded by a large courtyard with fountains and shaded walkways.', '2010', 'A landmark of contemporary Islamic architecture in Qatar, representing the country''s commitment to preserving Islamic cultural heritage within a modern context.', false, NULL, 'Contemporary Andalusian-Levantine', '2026-05-26 12:32:52.610071', '/models/katara-mosque.glb', 3000, NULL, NULL, false, false, false, 'Sunni') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (20, 'Shah Rukn-e-Alam Shrine', 'ضريح شاه ركن عالم', 'South Asia', 'Pakistan', 30.1978, 71.4753, 'Shrine', 'The magnificent 14th-century Sufi shrine of Saint Rukn-ud-Din Abul Fatah in Multan, a masterpiece of Tughluq architecture.', 'The Shrine of Shah Rukn-e-Alam in Multan, Pakistan, is one of the most magnificent examples of early Islamic monumental architecture in South Asia. Built between 1320 and 1324 CE during the Tughluq dynasty, it was constructed by Sultan Ghiyath ud-Din Tughluq as his own mausoleum but later given to the Sufi saint Rukn-ud-Din Abul Fatah (1251–1335 CE), who was a prominent figure of the Suhrawardiyya Sufi order. The shrine stands on a high octagonal base and is crowned with a massive dome. The exterior walls are decorated with elaborate geometric patterns in blue, white, and terracotta glazed tiles interspersed with carved woodwork. The main chamber contains the saint''s tomb and is perpetually visited by devoted pilgrims. The shrine dominates the skyline of Multan and is considered the jewel of the city.', '1324', 'One of the holiest Sufi shrines in Pakistan and a supreme example of Tughluq-era monumental Islamic architecture in the subcontinent.', false, NULL, 'Tughluq-Multan Islamic', '2026-05-26 12:32:52.610071', '/models/shah-rukn-e-alam.glb', NULL, NULL, NULL, false, false, false, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (21, 'Miqat Al-Sail Al-Kabeer', 'ميقات السيل الكبير', 'Arabian Peninsula', 'Saudi Arabia', 21.63262, 40.42683, 'Miqat', 'The miqat for pilgrims approaching Makkah from the direction of Najd and Ta''if, where ihram is assumed before entering the sacred precincts.', 'Miqat Al-Sail Al-Kabeer, also known as Qarn al-Manazil, is one of the five sacred boundary points (mawaqit) established by the Prophet Muhammad ﷺ for Hajj and Umrah. It is located approximately 80 km east of Makkah on the road from Ta''if, serving pilgrims arriving from Najd (central Arabia), the Arabian Gulf states, and travellers from the east. The miqat marks the boundary beyond which no Muslim intending to perform Hajj or Umrah may pass without entering the state of ihram — donning the white unsewn garments and making the intention (niyyah). The site today features a large mosque complex with ablution facilities, where pilgrims stop, change into ihram, and recite the talbiyah before continuing toward the Haram. The location corresponds to the wadi of Al-Sail Al-Kabeer, and is referenced in authenticated hadiths of the Prophet ﷺ.', '7th century CE', 'One of the five prophetically designated miqat boundary points for Hajj and Umrah; the entry point for all pilgrims arriving from Najd and the east.', false, NULL, 'Contemporary Islamic', '2026-05-26 12:32:52.610071', '/models/miqat-al-sail.glb', NULL, NULL, NULL, false, false, false, 'Universal') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (22, 'Shrine of Imam Ali', 'ضريح الإمام علي', 'Middle East', 'Iraq', 31.9961, 44.3098, 'Shrine', 'The golden-domed mausoleum of Imam Ali ibn Abi Talib in Najaf, one of the holiest sites in Islam.', 'The Shrine of Imam Ali (also known as the Imam Ali Mosque or the Holy Shrine of Ali ibn Abi Talib) is located in Najaf, Iraq, and marks the burial place of Ali ibn Abi Talib — cousin and son-in-law of the Prophet Muhammad ﷺ, the fourth Caliph of Islam. The shrine is among the holiest sites in Islam, drawing millions of pilgrims annually. The current structure dates largely from the Buyid, Safavid, and later periods, featuring a magnificent golden dome, gilded minarets, and vast iwan halls adorned with intricate mirror mosaic work (āina-kāri). The shrine complex is adjacent to Wadi Al-Salam, the largest cemetery in the world, where millions of Muslims seek to be buried near the Imam. Major expansions were carried out under the Safavid Shahs and in the 20th and 21st centuries.', '791 CE', 'One of the holiest sites in Islam, marking the burial place of Imam Ali ibn Abi Talib; a supreme pilgrimage destination for Muslims worldwide.', true, NULL, 'Islamic / Safavid Persian', '2026-05-26 12:32:52.610071', '/models/shrine-imam-ali.glb', NULL, NULL, NULL, false, false, false, 'Shia') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (23, 'Miqat Dhul Hulaifah', 'ميقات ذو الحليفة', 'Arabian Peninsula', 'Saudi Arabia', 24.41375, 39.54332, 'Miqat', 'The farthest miqat from Makkah, located near Madinah and designated for pilgrims travelling from al-Madinah al-Munawwarah.', 'Miqat Dhul Hulaifah, popularly known as Abyar Ali (Bir Ali), is the miqat designated by the Prophet Muhammad ﷺ for pilgrims setting out toward Makkah from the direction of al-Madinah al-Munawwarah. It is located approximately 9 km south of Madinah and is the farthest of the five mawaqit from the Kaaba (about 450 km). It is the miqat used by the Prophet ﷺ himself when he departed from Madinah for both the Farewell Pilgrimage and for Umrah. The site features Masjid Al-Shajarah (Mosque of the Tree), named after a large tree under which it is narrated the Prophet ﷺ rested. Today it is a large, modern mosque complex accommodating tens of thousands of pilgrims who stop here to change into ihram, perform ablution, make the intention of Hajj or Umrah, and recite the talbiyah before departing for Makkah.', '7th century CE', 'The miqat used by the Prophet Muhammad ﷺ himself; the farthest miqat from Makkah and the one designated for pilgrims from Madinah.', false, NULL, 'Contemporary Islamic', '2026-05-26 12:32:52.610071', '/models/miqat-dhul-hulaifah.glb', NULL, NULL, NULL, false, false, false, 'Universal') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (24, 'Miqat Al-Juhfah', 'ميقات الجحفة', 'Arabian Peninsula', 'Saudi Arabia', 22.70468, 39.14673, 'Miqat', 'The ancient miqat near Rabigh designated for pilgrims approaching Makkah from the north and west — from Syria, Egypt, and North Africa.', 'Miqat Al-Juhfah is one of the five mawaqit designated by the Prophet Muhammad ﷺ for the assumption of ihram before entering the Haram of Makkah. It is located near the modern town of Rabigh on the Red Sea coast, approximately 183 km northwest of Makkah. Historically, Al-Juhfah was a settlement on the ancient pilgrimage route from Syria and Egypt; after it fell into ruin, the nearby town of Rabigh became the practical miqat point. The miqat serves pilgrims arriving from Syria, Jordan, Egypt, North Africa, and the Levant. The site today features a large mosque (Masjid Al-Juhfah or Masjid Miqat Rabigh) where pilgrims perform ghusl, don ihram garments, and recite the talbiyah.', '7th century CE', 'The prophetically designated miqat for pilgrims from the Levant, Egypt, and North Africa; one of the five permanent boundary stations for Hajj and Umrah.', false, NULL, 'Contemporary Islamic', '2026-05-26 12:32:52.610071', '/models/miqat-al-juhfah.glb', NULL, NULL, NULL, false, false, false, 'Universal') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (25, 'Masjid Quba', 'مسجد قباء', 'Arabian Peninsula', 'Saudi Arabia', 24.4408, 39.616, 'Mosque', 'The first mosque ever built in Islam, established by the Prophet Muhammad ﷺ upon his arrival in Madinah in 622 CE.', 'Masjid Quba is the first mosque constructed in Islamic history. When the Prophet Muhammad ﷺ arrived in Madinah after the Hijra from Makkah in 622 CE, the first thing he did was lay the foundation of this mosque in the settlement of Quba on the outskirts of the city. He himself participated in carrying stones for its construction. The original structure was modest, but the mosque has been rebuilt and expanded multiple times — most recently in 1986 with a major Saudi renovation giving it its current form: gleaming white domes, four tall minarets, and spacious courtyards. The Prophet ﷺ stated that the reward of praying two rak''ahs in Masjid Quba is equivalent to performing one Umrah, making it one of the most spiritually significant mosques in Islam. It is located approximately 5 km south of Masjid An-Nabawi.', '622 CE', 'The first mosque ever built in Islam, founded by the Prophet Muhammad ﷺ himself; praying two rak''ahs here carries the reward of a complete Umrah.', true, NULL, 'Contemporary Arabian / Najdi', '2026-05-26 12:32:52.610071', '/models/masjid-quba.glb', 20000, 13500, NULL, false, false, false, 'Universal') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (26, 'Mount Arafat', 'جبل عرفات', 'Arabian Peninsula', 'Saudi Arabia', 21.3536, 39.9842, 'Pilgrimage Site', 'The sacred plain 20 km from Makkah where the Standing (Wuquf) — the essential rite of Hajj — takes place on 9 Dhul Hijjah.', 'Mount Arafat (Jabal Arafat), also called Jabal al-Rahmah (Mountain of Mercy), is a granite hill and surrounding plain approximately 20 km east of Makkah al-Mukarramah. It is the most essential site of the Hajj pilgrimage — the Prophet ﷺ declared: ""Hajj is Arafat."" Every year on 9 Dhul Hijjah, more than two million pilgrims gather on the plain from noon to sunset in supplication, dhikr, and repentance before Allah — a gathering described as a foretaste of the Day of Judgment. It was here that the Prophet ﷺ delivered his historic Farewell Sermon (Khutbat al-Wada) in 632 CE. It is also the site where the final verse of the Quran is believed to have been revealed: ""This day I have perfected for you your religion..."" (Quran 5:3). The Namirah Mosque on the western edge of the plain serves the millions of pilgrims who congregate there annually.', 'Primordial / 7th century CE', 'The pivotal site of Hajj — standing here on 9 Dhul Hijjah is the essential pillar of the pilgrimage; the Prophet ﷺ declared "Hajj is Arafat."', true, NULL, NULL, '2026-05-26 12:32:52.610071', '/models/mount-arafat.glb', NULL, NULL, NULL, false, false, false, 'Universal') ON CONFLICT DO NOTHING;

-- Reset sequence to max id + 1
SELECT pg_catalog.setval('public.sites_id_seq', (SELECT MAX(id) FROM public.sites), true);

-- ── Hotspots data ──────────────────────────────────────────────

INSERT INTO public.hotspots VALUES (6, 1, 'The Kaaba', 'The Kaaba is a cube-shaped structure at the center of Masjid Al-Haram. Muslims believe it was first built by Prophet Ibrahim (Abraham) and his son Ismail. Covered in black silk embroidered with gold Quranic verses (the Kiswa), it is the most sacred point in Islam. Muslims circumambulate (tawaf) around the Kaaba during Hajj and Umrah.', 0, 0.5, 0, 'الكعبة المشرفة', 'Originally built by Prophet Ibrahim; rebuilt multiple times', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.hotspots VALUES (7, 1, 'Black Stone', 'The Black Stone (Al-Hajar al-Aswad) is set in the eastern corner of the Kaaba. Islamic tradition holds that it fell from paradise and was originally pure white, darkening over centuries. Pilgrims attempt to touch or kiss it when possible. It is framed in a silver holder and marks the starting point for circumambulation of the Kaaba.', 0.3, 0.2, 0.3, 'الحجر الأسود', 'Pre-Islamic; mentioned in hadith of the Prophet', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.hotspots VALUES (8, 1, 'Zamzam Well', 'The Zamzam Well is a miraculous well located within the Masjid Al-Haram compound. According to Islamic tradition, it was miraculously created by Allah for Hagar (Hajar) and her infant son Ismail when they were left in the desert. The well has supplied water for over 4,000 years. Pilgrims drink Zamzam water as a religious practice.', -0.3, -0.2, 0.4, 'بئر زمزم', 'Over 4,000 years old; Islamic tradition traces to Prophet Ibrahim''s time', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.hotspots VALUES (9, 4, 'Golden Dome', 'The magnificent golden dome of the Dome of the Rock is 20 metres in diameter and 25 metres in height. Originally covered in gold, it was later covered in lead and then aluminum. In 1993, Jordan''s King Hussein donated 80 kg of gold to restore its golden appearance. The dome sits on a drum decorated with elaborate tile inscriptions.', 0, 1.3, 0, 'القبة الذهبية', 'Original dome: 691 CE; golden covering restored: 1993 CE', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.hotspots VALUES (10, 4, 'Foundation Stone', 'The Foundation Stone (al-Sakhrah al-Musharrafah) is the rock beneath the dome, one of the holiest sites in three Abrahamic faiths. In Islam, it is believed to be the spot from which Prophet Muhammad ascended to heaven during the Night Journey. It measures approximately 18 by 13 metres and is enclosed by a wooden screen.', 0, -0.1, 0, 'الصخرة المشرفة', 'Pre-Islamic; site of Prophet''s ascension during Isra wal Miraj (621 CE)', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.hotspots VALUES (11, 4, 'Byzantine Mosaics', 'The interior of the Dome of the Rock is adorned with spectacular Byzantine-style mosaics covering over 280 metres in the upper drum and arcade. Dating to the Umayyad period (691 CE), these mosaics feature intricate floral and jewel motifs without human figures, consistent with Islamic artistic tradition. They represent the finest surviving example of early Islamic decorative arts.', 0.7, 0.8, 0, 'الفسيفساء البيزنطية', '691 CE (Umayyad)', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.hotspots VALUES (12, 7, 'Striped Arches', 'The distinctive red-and-white voussoir arches of the Great Mosque of Cordoba are its most iconic architectural feature. This double-arch system was an innovative structural solution that allowed the builders to raise the ceiling height beyond what a single arch could support. The alternating red brick and white limestone creates a visually stunning rhythmic pattern.', 0, 0.6, -0.7, 'الأقواس المتشابكة', '784 CE (Abd al-Rahman I)', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.hotspots VALUES (13, 7, 'The Mihrab', 'The mihrab of the Great Mosque of Cordoba is considered one of the most beautiful mihrabs in the Islamic world. Constructed in 965 CE under Caliph Al-Hakam II, it is a masterpiece of Umayyad art. The horseshoe arch entrance is framed by elaborate marble columns and Byzantine-style mosaics commissioned from the Byzantine Emperor. The interior of the mihrab is a small octagonal chamber.', 0, 0.4, -0.9, 'المحراب', '965 CE (Al-Hakam II)', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.hotspots VALUES (14, 7, 'Forest of Columns', 'The prayer hall of the Great Mosque contains over 850 columns of jasper, onyx, marble, and granite, creating a hypnotic ''forest'' effect. Many columns were reused from earlier Roman and Visigothic structures. The regular grid of columns creates an infinite repetition of arches in every direction, producing a meditative visual effect that has inspired architects for over a millennium.', -0.5, 0.4, 0, 'غابة الأعمدة', '784-987 CE (multiple Umayyad rulers)', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.hotspots VALUES (15, 8, 'Court of the Lions', 'The Court of the Lions is the most celebrated space in the Alhambra, built by Emir Muhammad V in the 14th century. It features a central marble fountain supported by twelve sculpted lions, from which four channels of water radiate outward. The surrounding gallery features 124 slender marble columns with intricately carved muqarnas capitals. The fountain represents the Garden of Paradise.', 0, 0.1, 0, 'فناء الأسود', 'c. 1370 CE (Muhammad V)', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.hotspots VALUES (16, 8, 'Muqarnas Ceiling', 'The muqarnas ceiling of the Hall of the Abencerrages is one of the most spectacular architectural features in the Alhambra. Muqarnas are stalactite-like three-dimensional decorative vaulting elements used extensively in Islamic architecture. This ceiling contains over 5,000 individual plaster cells arranged in concentric rings, creating a breathtaking honeycomb effect that seems to dissolve into infinity.', 0.5, 1, 0.3, 'المقرنصات', '14th century CE (Nasrid dynasty)', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.hotspots VALUES (17, 8, 'Arabesque Stucco', 'The walls of the Alhambra are covered in intricate stucco arabesque panels featuring flowing geometric patterns, vegetal motifs, and calligraphic inscriptions from the Quran and Nasrid poetry. The famous Nasrid motto ''There is no victor but Allah'' (Wa la ghalib illa Allah) is repeated throughout. These stucco panels were originally brilliantly painted in red, blue, gold, and other colors.', -0.6, 0.7, 0.4, 'الزخارف الجصية', '13th-14th century CE (Nasrid dynasty)', NULL) ON CONFLICT DO NOTHING;

INSERT INTO public.sites VALUES (27, 'Sultan Salahuddin Abdul Aziz Shah Mosque', 'مسجد السلطان صلاح الدين عبد العزيز شاه', 'Southeast Asia', 'Malaysia', 3.0764, 101.5172, 'mosque', 'The largest mosque in Malaysia, known as the Blue Mosque for its iconic blue and silver dome.', 'The Sultan Salahuddin Abdul Aziz Shah Mosque, commonly known as the Blue Mosque, is the state mosque of Selangor and the largest mosque in Malaysia. Situated on a 35-acre hilltop in Shah Alam, it was commissioned by Sultan Salahuddin Abdul Aziz Shah when he declared Shah Alam the capital of Selangor in 1974. Construction began in 1982 and was completed in 1988. The mosque features one of the world''s largest religious domes at 51.2 metres in diameter, clad in blue and silver panels. Its four minarets stand 142.3 metres tall, once ranking among the world''s tallest. The interior includes fine Arabic calligraphy by Egyptian calligrapher Sheikh Abdel Moneim Mohamed Ali El Sharkawi, blue stained glass windows, and a timber ceiling in a crisscrossing pattern. The design blends Malay and Modernist Islamic architecture. It overlooks the Garden of Islamic Arts, a landscaped park inspired by the Quranic Garden of Paradise.', '1982-1988 CE', 'Largest mosque in Malaysia; second largest in Southeast Asia; iconic Blue Mosque of Malaysia', false, NULL, 'Malay-Islamic Modernist', NOW(), '/models/sultan-salahuddin-mosque.glb', 24000, 141640, NULL, false, false, false, 'Sunni') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (28, 'Great Mosque of Tirana', 'جامع نامازغاه الكبير', 'Balkans', 'Albania', 41.3275, 19.8187, 'mosque', 'The largest mosque in the Balkans, opened in 2024 in central Tirana.', 'The Great Mosque of Tirana, also known as the Namazgah Mosque, is the largest mosque in the Balkans. Located in central Tirana near Skanderbeg Square, its foundation stone was laid in 1992 and construction began in 2015. Officially opened on 10 October 2024, the mosque was designed by Turkish architect Muharrem Hilmi Senalp in a Classical Ottoman style inspired by Istanbul''s Blue Mosque. It features four 50-metre minarets and a 30-metre central dome. With a capacity of 10,000 worshippers (8,000 inside, 2,000 outside), it serves as both a religious centre and a cultural hub, including a Museum of Coexistence that celebrates Albania''s tradition of religious harmony. The mosque was built adjacent to the Catholic and Orthodox cathedrals, deliberately forming a triangle representing interfaith coexistence.', '2015-2024 CE', 'Largest mosque in the Balkans; symbol of Albanian religious harmony and interfaith coexistence', false, NULL, 'Classical Ottoman', NOW(), '/models/great-mosque-of-tirana.glb', 10000, 10000, NULL, false, false, false, 'Sunni') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (29, 'Afsonalar Vodiysi Mosque', 'مسجد وادي الأساطير', 'Central Asia', 'Uzbekistan', 40.9985, 71.6237, 'mosque', 'A modern mosque within the Valley of Legends cultural park in Namangan, Uzbekistan, celebrated for its striking Central Asian Islamic architecture.', 'The Afsonalar Vodiysi Mosque, also known as the Yusufxon o''g''li Qosimxon Mosque, is situated within the Valley of Legends (Afsonalar Vodiysi) cultural and recreational park in Namangan, the second-largest city in Uzbekistan''s Fergana Valley. The mosque serves as both a spiritual centre and an architectural landmark, blending modern construction techniques with traditional Central Asian Islamic design motifs. Its prominent dome and minaret reflect the Timurid architectural heritage of the region, while the surrounding parkland provides a serene setting that draws visitors from across the Fergana Valley. The mosque stands as a symbol of Uzbekistan''s post-independence cultural renaissance, representing the renewed commitment to Islamic heritage in Central Asia following the Soviet era.', '21st century CE', 'A significant modern mosque in Central Asia representing Uzbekistan''s cultural revival and Islamic architectural heritage in the Fergana Valley.', false, '/site-images/afsonalar-vodiysi.jpg', 'Modern Central Asian Islamic', NOW(), '/models/afsonalar-vodiysi.glb', 500, 2000, NULL, false, false, false, 'Sunni') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (30, 'Kudhu Miskiyy', 'مسجد كودهو', 'South Asia', 'Maldives', 0.82, 73.25, 'mosque', 'An abandoned traditional mosque on Kondey island in Gaafu Alifu Atoll, Maldives, built by descendants of the master builders of Male''s Old Friday Mosque.', 'The Kudhu Miskiyy is a traditional Maldivian mosque located on Kondey island in Gaafu Alifu Atoll (North Huvadhu), in the southern reaches of the Maldives archipelago. According to local oral history, the mosque was built by Ali and Mahmud Maavadi Kaleyfaan, skilled craftsmen from Kondey who had earlier helped construct the famous Hukuru Miskiyy (Old Friday Mosque) in Male, the capital. After completing their work in Male, they returned to their home island and built this mosque with the remaining materials. The mosque has since been expanded beyond its original footprint, though elements of the older structure remain visible from the back. Today it stands abandoned, a silent witness to the maritime Islamic heritage of the Maldivian atolls and the once-flourishing tradition of coral-stone mosque building that defined the nation''s architectural identity.', 'Traditional period (pre-modern)', 'A rare surviving example of traditional Maldivian mosque architecture in the outer atolls, linked by oral tradition to the master builders of Male''s UNESCO-listed Old Friday Mosque.', false, '/site-images/kudhu-miskiyy.jpg', 'Traditional Maldivian', NOW(), '/models/kudhu-miskiyy.glb', 50, 150, NULL, false, false, false, 'Sunni') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (31, 'Ban Tok Chao Mosque', 'مسجد بان توك تشاو', 'Southeast Asia', 'Thailand', 9.1333, 99.3317, 'mosque', 'A distinctive mosque in Surat Thani, Thailand, originally constructed on wooden stilts with a no-longer-used upper-floor prayer hall, later converted in 2014 to its current form.', 'The Ban Tok Chao Mosque in Surat Thani province, southern Thailand, is a remarkable example of syncretic Islamic architecture that blends Malay-Muslim, Thai Buddhist, and Arabian artistic traditions. The mosque was originally built entirely on wooden stilts, a construction technique common in the wetland and coastal regions of southern Thailand. Its upper floor once served as the prayer hall, but is no longer in use. In 2014, a brick wall was erected around the ground floor — the existing stilt locks are still visible — and the ground level was converted into the present prayer hall. The roof carries a unique Muslim-style decorative scheme characteristic of southern Thai mosques: the gables bear paintings of Garuda, the mythical bird and national emblem of Thailand; Al-Buraq, the winged horse-like creature from Islamic tradition that carried the Prophet Muhammad on his Night Journey; and a female face adorned in an Arabic-style hijab. This extraordinary combination of symbols reflects the deep intercultural history of Islam in Thailand, where Malay-Muslim communities have long coexisted within a predominantly Buddhist kingdom, producing architecture that speaks in multiple visual languages simultaneously.', 'Traditional (pre-2014 conversion)', 'A rare surviving example of stilt-based mosque architecture in Southeast Asia, with uniquely syncretic decorative art blending Thai, Islamic, and Malay visual traditions.', false, '/site-images/ban-tok-chao.jpg', 'Syncretic Thai-Malay-Islamic', NOW(), '/models/ban-tok-chao.glb', 80, 300, NULL, false, false, false, 'Sunni') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (32, 'Al Mohamadi Mosque', 'مسجد المحمدي', 'North Africa', 'Morocco', 33.57, -7.60, 'mosque', 'A historic mosque in the Habous district of Casablanca, Morocco, commissioned by King Mohammed V, exemplifying early 20th-century Moroccan colonial-era Islamic architecture.', 'The Al Mohamadi Mosque stands in the Habous district (New Medina) of Casablanca, a neighbourhood built during the French Protectorate era to accommodate the growing Moroccan population. Commissioned by King Mohammed V of Morocco, the mosque reflects the distinctive architectural synthesis of that period — blending traditional Moroccan Islamic elements such as horseshoe arches, zellige tilework, and carved stucco with the urban planning sensibilities of early 20th-century Casablanca. The Habous district itself is renowned for its orderly streets, artisan workshops, and bustling souks, and the mosque serves as both a spiritual anchor and a historical marker of Morocco''s path toward independence. As one of the landmark mosques commissioned by the beloved monarch who would later lead the nation to independence, the Al Mohamadi Mosque holds a special place in the collective memory of Casablanca''s residents.', '20th century CE', 'Commissioned by King Mohammed V, a symbol of Moroccan national identity and the colonial-era architectural heritage of Casablanca''s Habous district.', false, '/site-images/al-mohamadi-mosque.jpg', 'Moroccan Colonial-Era Islamic', NOW(), '/models/al-mohamadi-mosque.glb', 300, 800, NULL, false, false, false, 'Sunni') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (33, 'White Mosque', 'المسجد الأبيض', 'Central Asia', 'Russia', 54.97, 49.06, 'mosque', 'A striking modern mosque at the Bolgar Historical and Archaeological Complex in Tatarstan, Russia, built to commemorate the region''s Islamic heritage and Volga Bulgar history.', 'The White Mosque stands at the Bolgar Historical and Archaeological Complex, a UNESCO World Heritage Site on the banks of the Volga River in the Republic of Tatarstan, Russia. This modern mosque was constructed to honour the region''s profound Islamic heritage as the centre of the Volga Bulgaria, one of the earliest Islamic states in Eastern Europe, which adopted Islam in 922 CE under Khan Almish. The mosque''s pristine white architecture stands in deliberate contrast to the ancient ruins of Bolgar that surround it — the remains of the medieval capital of the Volga Bulgars, a Turkic people who played a pivotal role in the Islamisation of the Eurasian steppe. The Bolgar complex, known as the ''northern Mecca'' in Russian Muslim tradition, attracts pilgrims and visitors who come to connect with this early chapter of Islamic civilisation in Eastern Europe. The White Mosque serves as a living prayer space and a powerful symbol of the continuity of Islamic faith in the Volga region, bridging the medieval past of the Bolgar Khanate with the vibrant Muslim community of modern Tatarstan.', '2012 CE', 'Part of the Bolgar UNESCO World Heritage Site; commemorates the 922 CE adoption of Islam by the Volga Bulgars, one of the earliest Islamic states in Eastern Europe.', false, '/site-images/white-mosque-bolgar.jpg', 'Modern Tatar-Islamic', NOW(), '/models/white-mosque-tatarstan.glb', 200, 1500, NULL, false, false, false, 'Sunni') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (34, 'Mina', 'منى', 'Arabian Peninsula', 'Saudi Arabia', 21.4133, 39.8936, 'Pilgrimage Site', 'A valley six kilometres east of Masjid al-Haram in Makkah, known as the Tent City of Hajj.', 'Mina (Arabic: منى) is a valley six kilometres east of the Masjid al-Haram in Makkah. It is where Hajj pilgrims sleep overnight on the 8th, 11th, 12th (and some even on the 13th) of Dhul Hijjah. The valley of Mina contains the Jamarat, the three stone pillars which are pelted by pilgrims as part of the rituals of Hajj. Mina is referenced in Surah Baqarah in the Quran: "And remember Allah during [specific] numbered days. Then whoever hastens [his departure] in two days – there is no sin upon him; and whoever delays [until the third] – there is no sin upon him – for him who fears Allah . And fear Allah and know that unto Him you will be gathered." [2:203]. The name Mina is derived from the root letters ma-na-ya which means "to be put to the test" or "to undergo" — connected to the test that Prophet Ebrahim (عليه السلام) had to undergo when he was ordered to sacrifice his son. When his resolve was proven, a ram was sacrificed in place. The word can also mean "to flow" because the blood of sacrificial animals flows here during Eidul Adha. Around 3 million pilgrims stay annually in Mina in more than 100,000 air-conditioned tents, leading to Mina also being known as the "Tent City". In this very spot the First Pledge by a group of 12 Men from Madinah was taken, marking the turning point and revolution of Yathrib which later became the luminous city of Madinah.', 'Ancient', 'Essential Hajj pilgrimage site; home to the Jamarat and the famous Tent City accommodating millions of pilgrims', false, NULL, 'Modern tent infrastructure', NOW(), '/models/mina-tent-city.glb', 3000000, 20000000, NULL, false, false, false, 'Sunni') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (35, 'Jamarat', 'الجمرات', 'Arabian Peninsula', 'Saudi Arabia', 21.4200, 39.8600, 'Pilgrimage Site', 'The three stone pillars in Mina that are stoned by pilgrims during the ritual of Rami al-Jamarat in Hajj.', 'The Jamarat are three stone pillars situated in the valley of Mina, near Makkah, Saudi Arabia. They represent the locations where Prophet Ebrahim (عليه السلام) was tempted by Satan (Iblis) to disobey Allah''s command to sacrifice his son, Ismail (عليه السلام). Each time Satan appeared, Prophet Ebrahim drove him away by throwing stones at him. The three pillars are known as Jamrat al-Ula (the first), Jamrat al-Wusta (the middle), and Jamrat al-Aqaba (the largest). During the days of Hajj (10th, 11th, and 12th of Dhul Hijjah), pilgrims perform the ritual of Rami al-Jamarat — symbolically stoning Satan and reaffirming their rejection of evil. The Jamarat Bridge, a multi-level pedestrian bridge, was constructed to safely accommodate the millions of pilgrims who perform this ritual. The largest pillar, Jamrat al-Aqaba, is stoned on the 10th of Dhul Hijjah (Yawm al-Nahr), while all three are stoned on the 11th and 12th. The ritual represents the triumph of faith and obedience to Allah over the whispers of temptation.', 'Ancient', 'Sacred Hajj ritual site; symbol of resisting temptation and the triumph of faith over evil', false, NULL, 'Ancient stone pillars with modern bridge infrastructure', NOW(), '/models/jamarat.glb', 3000000, 50000, NULL, false, false, false, 'Sunni') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (36, 'Masjid Nimrah', 'مسجد نمرة', 'Arabian Peninsula', 'Saudi Arabia', 21.3733, 39.9400, 'mosque', 'The mosque in the plain of Arafat where the Prophet Muhammad (PBUH) delivered his Farewell Sermon during Hajj.', 'Masjid Nimrah is situated on the plain of Arafat, approximately 20 kilometres east of Makkah, Saudi Arabia. It is one of the most significant mosques in the Islamic world due to its direct connection to the Hajj pilgrimage. On the 9th of Dhul Hijjah, the Day of Arafat, the imam of Masjid Nimrah delivers the Khutbah (sermon) of Wuquf — the standing at Arafat — and leads the combined Dhuhr and Asr prayers in congregation. This mirrors the practice of the Prophet Muhammad (PBUH), who delivered his historic Farewell Sermon at this very location during his final Hajj in 10 AH (632 CE), addressing over 100,000 companions. The sermon covered fundamental principles of Islam including the sanctity of life, property, and honour; the abolition of usury; the equality of all Muslims; and the rights of women. The current mosque structure was built to accommodate the vast number of pilgrims who gather here on the Day of Arafat, with modern facilities and a large prayer hall. It stands as a living monument to the final public address of the Prophet and the spiritual climax of the Hajj pilgrimage.', '10 AH (632 CE — original location)', 'Site of the Prophet''s Farewell Sermon; the khutbah and combined prayers of Wuquf at Arafat are performed here annually on the Day of Arafat', false, NULL, 'Modern Islamic with traditional elements', NOW(), '/models/masjid-nimrah.glb', 300000, 50000, NULL, false, false, false, 'Sunni') ON CONFLICT DO NOTHING;
INSERT INTO public.sites VALUES (37, 'Muzdalifah', 'مزدلفة', 'Arabian Peninsula', 'Saudi Arabia', 21.3933, 39.8933, 'Pilgrimage Site', 'An open plain between Mina and Arafat where Hajj pilgrims spend the night after the Day of Arafat, collecting pebbles for the Jamarat ritual.', 'Muzdalifah is an open plain situated between the plains of Mina and Arafat, approximately 8 kilometres from Mina and 7 kilometres from Arafat, in the Makkah region of Saudi Arabia. It is one of the most important locations in the Hajj pilgrimage, serving as the overnight resting place for pilgrims on the night of the 9th to the 10th of Dhul Hijjah — after the Day of Arafat (Wuquf) and before the ritual stoning at the Jamarat. Pilgrims arrive at Muzdalifah after sunset from Arafat, where they perform the combined Maghrib and Isha prayers. They spend the night under the open sky (or in tents), engaging in prayer, reflection, and rest. The most distinctive activity at Muzdalifah is the collection of small pebbles (around 49 to 70 stones) from the ground, which are used the next day for the Rami al-Jamarat ritual — the symbolic stoning of Satan at the three stone pillars in Mina. The plain is also known as al-Mashar al-Haram (the Sacred Monument), and it holds deep spiritual significance as a place of transition between the profound devotion of Arafat and the active rituals of Mina.', 'Ancient', 'Essential Hajj pilgrimage site; overnight resting place between Arafat and Mina; pilgrims collect pebbles here for the Jamarat stoning ritual', false, '/site-images/muzdalifah.png', 'Open plain with modern pilgrim infrastructure', NOW(), NULL, 3000000, 25000000, NULL, false, false, false, 'Sunni') ON CONFLICT DO NOTHING;

-- Reset sequence to max id + 1
SELECT pg_catalog.setval('public.sites_id_seq', (SELECT MAX(id) FROM public.sites), true);
SELECT pg_catalog.setval('public.hotspots_id_seq', (SELECT MAX(id) FROM public.hotspots), true);
